spring.application.name=dt-money


#Emdereco do banco de dados
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL

#Usuario do banco de dados
spring.datasource.username=rm568007

#Senha do banco de dados
spring.datasource.password=301001

#Mostra instrucoes SQL executadas no banco
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update
